// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bs1996_ts_nart_cpp
double bs1996_ts_nart_cpp(const arma::mat& y1, const arma::mat& y2);
RcppExport SEXP _HDNRA_bs1996_ts_nart_cpp(SEXP y1SEXP, SEXP y2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y2(y2SEXP);
    rcpp_result_gen = Rcpp::wrap(bs1996_ts_nart_cpp(y1, y2));
    return rcpp_result_gen;
END_RCPP
}
// cq2010_tsbf_nabt_cpp
arma::vec cq2010_tsbf_nabt_cpp(const arma::mat& y1, const arma::mat& y2);
RcppExport SEXP _HDNRA_cq2010_tsbf_nabt_cpp(SEXP y1SEXP, SEXP y2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y2(y2SEXP);
    rcpp_result_gen = Rcpp::wrap(cq2010_tsbf_nabt_cpp(y1, y2));
    return rcpp_result_gen;
END_RCPP
}
// zgzc2020_ts_2cnrt_cpp
arma::vec zgzc2020_ts_2cnrt_cpp(const arma::mat& y1, const arma::mat& y2);
RcppExport SEXP _HDNRA_zgzc2020_ts_2cnrt_cpp(SEXP y1SEXP, SEXP y2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y2(y2SEXP);
    rcpp_result_gen = Rcpp::wrap(zgzc2020_ts_2cnrt_cpp(y1, y2));
    return rcpp_result_gen;
END_RCPP
}
// zzgz2021_tsbf_2cnrt_cpp
arma::vec zzgz2021_tsbf_2cnrt_cpp(const arma::mat& y1, const arma::mat& y2);
RcppExport SEXP _HDNRA_zzgz2021_tsbf_2cnrt_cpp(SEXP y1SEXP, SEXP y2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y2(y2SEXP);
    rcpp_result_gen = Rcpp::wrap(zzgz2021_tsbf_2cnrt_cpp(y1, y2));
    return rcpp_result_gen;
END_RCPP
}
// zz2022_ts_3cnrt_cpp
arma::vec zz2022_ts_3cnrt_cpp(const arma::mat& y1, const arma::mat& y2);
RcppExport SEXP _HDNRA_zz2022_ts_3cnrt_cpp(SEXP y1SEXP, SEXP y2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y2(y2SEXP);
    rcpp_result_gen = Rcpp::wrap(zz2022_ts_3cnrt_cpp(y1, y2));
    return rcpp_result_gen;
END_RCPP
}
// zz2022_tsbf_3cnrt_cpp
arma::vec zz2022_tsbf_3cnrt_cpp(const arma::mat& y1, const arma::mat& y2);
RcppExport SEXP _HDNRA_zz2022_tsbf_3cnrt_cpp(SEXP y1SEXP, SEXP y2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y2(y2SEXP);
    rcpp_result_gen = Rcpp::wrap(zz2022_tsbf_3cnrt_cpp(y1, y2));
    return rcpp_result_gen;
END_RCPP
}
// zwz2023_tsbf_2cnrt_cpp
arma::vec zwz2023_tsbf_2cnrt_cpp(const arma::mat& y1, const arma::mat& y2);
RcppExport SEXP _HDNRA_zwz2023_tsbf_2cnrt_cpp(SEXP y1SEXP, SEXP y2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y2(y2SEXP);
    rcpp_result_gen = Rcpp::wrap(zwz2023_tsbf_2cnrt_cpp(y1, y2));
    return rcpp_result_gen;
END_RCPP
}
// sd2008_ts_nabt_cpp
arma::vec sd2008_ts_nabt_cpp(const arma::mat& y1, const arma::mat& y2);
RcppExport SEXP _HDNRA_sd2008_ts_nabt_cpp(SEXP y1SEXP, SEXP y2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y2(y2SEXP);
    rcpp_result_gen = Rcpp::wrap(sd2008_ts_nabt_cpp(y1, y2));
    return rcpp_result_gen;
END_RCPP
}
// skk2013_tsbf_nabt_cpp
arma::vec skk2013_tsbf_nabt_cpp(const arma::mat& y1, const arma::mat& y2);
RcppExport SEXP _HDNRA_skk2013_tsbf_nabt_cpp(SEXP y1SEXP, SEXP y2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y2(y2SEXP);
    rcpp_result_gen = Rcpp::wrap(skk2013_tsbf_nabt_cpp(y1, y2));
    return rcpp_result_gen;
END_RCPP
}
// zzz2020_ts_2cnrt_cpp
arma::vec zzz2020_ts_2cnrt_cpp(const arma::mat& y1, const arma::mat& y2);
RcppExport SEXP _HDNRA_zzz2020_ts_2cnrt_cpp(SEXP y1SEXP, SEXP y2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y2(y2SEXP);
    rcpp_result_gen = Rcpp::wrap(zzz2020_ts_2cnrt_cpp(y1, y2));
    return rcpp_result_gen;
END_RCPP
}
// zzz2023_tsbf_2cnrt_cpp
arma::vec zzz2023_tsbf_2cnrt_cpp(const arma::mat& y1, const arma::mat& y2);
RcppExport SEXP _HDNRA_zzz2023_tsbf_2cnrt_cpp(SEXP y1SEXP, SEXP y2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y2(y2SEXP);
    rcpp_result_gen = Rcpp::wrap(zzz2023_tsbf_2cnrt_cpp(y1, y2));
    return rcpp_result_gen;
END_RCPP
}
// s2007_ks_nabt_cpp
arma::vec s2007_ks_nabt_cpp(List Y, const arma::vec& n, int p);
RcppExport SEXP _HDNRA_s2007_ks_nabt_cpp(SEXP YSEXP, SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(s2007_ks_nabt_cpp(Y, n, p));
    return rcpp_result_gen;
END_RCPP
}
// fhw2004_glht_nabt_cpp
double fhw2004_glht_nabt_cpp(List Y, const arma::mat& X, const arma::mat& C, const arma::vec& n, int p);
RcppExport SEXP _HDNRA_fhw2004_glht_nabt_cpp(SEXP YSEXP, SEXP XSEXP, SEXP CSEXP, SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(fhw2004_glht_nabt_cpp(Y, X, C, n, p));
    return rcpp_result_gen;
END_RCPP
}
// sf2006_glht_nabt_cpp
double sf2006_glht_nabt_cpp(List Y, const arma::mat& X, const arma::mat& C, const arma::vec& n, int p);
RcppExport SEXP _HDNRA_sf2006_glht_nabt_cpp(SEXP YSEXP, SEXP XSEXP, SEXP CSEXP, SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(sf2006_glht_nabt_cpp(Y, X, C, n, p));
    return rcpp_result_gen;
END_RCPP
}
// ys2012_glht_nabt_cpp
arma::vec ys2012_glht_nabt_cpp(const Rcpp::List& Y, const arma::mat& X, const arma::mat& C, const arma::vec& n, int p);
RcppExport SEXP _HDNRA_ys2012_glht_nabt_cpp(SEXP YSEXP, SEXP XSEXP, SEXP CSEXP, SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(ys2012_glht_nabt_cpp(Y, X, C, n, p));
    return rcpp_result_gen;
END_RCPP
}
// zgz2017_glhtbf_nabt_cpp
arma::vec zgz2017_glhtbf_nabt_cpp(List Y, const arma::mat& tG, const arma::vec& n, int p);
RcppExport SEXP _HDNRA_zgz2017_glhtbf_nabt_cpp(SEXP YSEXP, SEXP tGSEXP, SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tG(tGSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(zgz2017_glhtbf_nabt_cpp(Y, tG, n, p));
    return rcpp_result_gen;
END_RCPP
}
// zgz2017_glht_2cnrt_cpp
arma::vec zgz2017_glht_2cnrt_cpp(List Y, const arma::mat& tG, const arma::vec& n, int p);
RcppExport SEXP _HDNRA_zgz2017_glht_2cnrt_cpp(SEXP YSEXP, SEXP tGSEXP, SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tG(tGSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(zgz2017_glht_2cnrt_cpp(Y, tG, n, p));
    return rcpp_result_gen;
END_RCPP
}
// zzg2022_glhtbf_2cnrt_cpp
arma::vec zzg2022_glhtbf_2cnrt_cpp(List Y, const arma::mat& tG, const arma::vec& n, int p);
RcppExport SEXP _HDNRA_zzg2022_glhtbf_2cnrt_cpp(SEXP YSEXP, SEXP tGSEXP, SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tG(tGSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(zzg2022_glhtbf_2cnrt_cpp(Y, tG, n, p));
    return rcpp_result_gen;
END_RCPP
}
// zz2022_glht_3cnrt_cpp
arma::vec zz2022_glht_3cnrt_cpp(List Y, const arma::mat& tG, const arma::vec& n, int p);
RcppExport SEXP _HDNRA_zz2022_glht_3cnrt_cpp(SEXP YSEXP, SEXP tGSEXP, SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tG(tGSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(zz2022_glht_3cnrt_cpp(Y, tG, n, p));
    return rcpp_result_gen;
END_RCPP
}
// zz2022_glhtbf_3cnrt_cpp
arma::vec zz2022_glhtbf_3cnrt_cpp(const Rcpp::List& Y, const arma::mat& tG, const arma::vec& n, int p);
RcppExport SEXP _HDNRA_zz2022_glhtbf_3cnrt_cpp(SEXP YSEXP, SEXP tGSEXP, SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tG(tGSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(zz2022_glhtbf_3cnrt_cpp(Y, tG, n, p));
    return rcpp_result_gen;
END_RCPP
}
// zzz2022_glht_2cnrt_cpp
arma::vec zzz2022_glht_2cnrt_cpp(const Rcpp::List& Y, const arma::mat& X, const arma::mat& C, const arma::vec& n, int p);
RcppExport SEXP _HDNRA_zzz2022_glht_2cnrt_cpp(SEXP YSEXP, SEXP XSEXP, SEXP CSEXP, SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(zzz2022_glht_2cnrt_cpp(Y, X, C, n, p));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HDNRA_bs1996_ts_nart_cpp", (DL_FUNC) &_HDNRA_bs1996_ts_nart_cpp, 2},
    {"_HDNRA_cq2010_tsbf_nabt_cpp", (DL_FUNC) &_HDNRA_cq2010_tsbf_nabt_cpp, 2},
    {"_HDNRA_zgzc2020_ts_2cnrt_cpp", (DL_FUNC) &_HDNRA_zgzc2020_ts_2cnrt_cpp, 2},
    {"_HDNRA_zzgz2021_tsbf_2cnrt_cpp", (DL_FUNC) &_HDNRA_zzgz2021_tsbf_2cnrt_cpp, 2},
    {"_HDNRA_zz2022_ts_3cnrt_cpp", (DL_FUNC) &_HDNRA_zz2022_ts_3cnrt_cpp, 2},
    {"_HDNRA_zz2022_tsbf_3cnrt_cpp", (DL_FUNC) &_HDNRA_zz2022_tsbf_3cnrt_cpp, 2},
    {"_HDNRA_zwz2023_tsbf_2cnrt_cpp", (DL_FUNC) &_HDNRA_zwz2023_tsbf_2cnrt_cpp, 2},
    {"_HDNRA_sd2008_ts_nabt_cpp", (DL_FUNC) &_HDNRA_sd2008_ts_nabt_cpp, 2},
    {"_HDNRA_skk2013_tsbf_nabt_cpp", (DL_FUNC) &_HDNRA_skk2013_tsbf_nabt_cpp, 2},
    {"_HDNRA_zzz2020_ts_2cnrt_cpp", (DL_FUNC) &_HDNRA_zzz2020_ts_2cnrt_cpp, 2},
    {"_HDNRA_zzz2023_tsbf_2cnrt_cpp", (DL_FUNC) &_HDNRA_zzz2023_tsbf_2cnrt_cpp, 2},
    {"_HDNRA_s2007_ks_nabt_cpp", (DL_FUNC) &_HDNRA_s2007_ks_nabt_cpp, 3},
    {"_HDNRA_fhw2004_glht_nabt_cpp", (DL_FUNC) &_HDNRA_fhw2004_glht_nabt_cpp, 5},
    {"_HDNRA_sf2006_glht_nabt_cpp", (DL_FUNC) &_HDNRA_sf2006_glht_nabt_cpp, 5},
    {"_HDNRA_ys2012_glht_nabt_cpp", (DL_FUNC) &_HDNRA_ys2012_glht_nabt_cpp, 5},
    {"_HDNRA_zgz2017_glhtbf_nabt_cpp", (DL_FUNC) &_HDNRA_zgz2017_glhtbf_nabt_cpp, 4},
    {"_HDNRA_zgz2017_glht_2cnrt_cpp", (DL_FUNC) &_HDNRA_zgz2017_glht_2cnrt_cpp, 4},
    {"_HDNRA_zzg2022_glhtbf_2cnrt_cpp", (DL_FUNC) &_HDNRA_zzg2022_glhtbf_2cnrt_cpp, 4},
    {"_HDNRA_zz2022_glht_3cnrt_cpp", (DL_FUNC) &_HDNRA_zz2022_glht_3cnrt_cpp, 4},
    {"_HDNRA_zz2022_glhtbf_3cnrt_cpp", (DL_FUNC) &_HDNRA_zz2022_glhtbf_3cnrt_cpp, 4},
    {"_HDNRA_zzz2022_glht_2cnrt_cpp", (DL_FUNC) &_HDNRA_zzz2022_glht_2cnrt_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_HDNRA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
